/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.YearMonth;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author akmal
 */
public class KelolaPenggajian extends javax.swing.JFrame {
        private static final String URL = "jdbc:mysql://localhost/db_absensi";
        private static final String USERNAME = "root";
        private static final String PASSWORD = "";
        private Connection koneksi;
        private Statement stat;
    /**
     * Creates new form KelolaPenggajian
     */
    public KelolaPenggajian() {
        initComponents();
        koneksiDB();
        table();
        
        Calendar calendar = Calendar.getInstance();
        int tahunIni = calendar.get(Calendar.YEAR);
        tahunTF.setText("" + tahunIni);
        
        int bulanIni = calendar.get(Calendar.MONTH) + 1;
        bulanTF.setText("" + bulanIni);
    }
    
    private void koneksiDB(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            koneksi = DriverManager.getConnection(URL, USERNAME, PASSWORD);
            stat = koneksi.createStatement(); // Menghapus deklarasi tipe data Statement
            System.out.println("Koneksi ke database berhasil");
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("Koneksi ke database gagal: " + e.getMessage());
        }
    }
    
    private void table(){
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("No");        
        tb.addColumn("Kode Karyawan");
        tb.addColumn("Nama Karyawan");
        karyawanTB.setModel(tb);
        
        try{
            ResultSet res = stat.executeQuery("SELECT * FROM `karyawan`");
            int no = 1;
            while(res.next())
            {
               tb.addRow(new Object[]{
                   no++,
                   res.getString("kode_karyawan"),
                   res.getString("nama_karyawan"),
               });
            }
        }catch (Exception e) {
            System.out.println("Gagal Query: " + e.getMessage());
        }
    }
    
    private void kosongkan(){
        kdTF.setText("");
        
        gajiPokokTF.setText("");
        bonusTF.setText("");
        totalTF.setText("");
        
        jmTF.setText("");
        jtTF.setText("");
        jhsTF.setText("");
        jumlahTotalGajiH.setText("");
        totalPotonganTerlambat.setText("");
        totalPotongan.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bulanTF = new javax.swing.JTextField();
        tahunTF = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        gajiPokokTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bonusTF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        totalTF = new javax.swing.JTextField();
        kdTF = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jmTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jumlahTotalGajiH = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jhsTF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        totalPotonganTerlambat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        totalPotongan = new javax.swing.JTextField();
        hitungTotalBTN = new javax.swing.JButton();
        simpanBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        kembaliBTN = new javax.swing.JButton();
        hitungBTN1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        karyawanTB = new javax.swing.JTable();
        kembaliBTN1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(877, 566));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("DATA KARYAWAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("REKAP ABSENSI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("PERIZINAN");
        jButton4.setIconTextGap(41);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("PENGGAJIAN");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("LOGOUT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/gambar/logo3.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/gambar/684833.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("HALAMAN KELOLA PENGGAJIAN");

        jLabel5.setText("Selamat datang di Aplikasi Absensi dan Penilaian Karyawan ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("KELOLA PENGGAJIAN");

        jLabel6.setText("Bulan");

        jLabel7.setText("Tahun");

        tahunTF.setText("2023");
        tahunTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunTFActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Gaji Pokok");

        gajiPokokTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gajiPokokTFActionPerformed(evt);
            }
        });

        jLabel10.setText("Bonus");

        jLabel16.setText("Total Gaji");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(46, 46, 46)
                        .addComponent(totalTF, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gajiPokokTF)
                            .addComponent(bonusTF))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(gajiPokokTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(bonusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Jumlah Masuk");

        jmTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTFActionPerformed(evt);
            }
        });

        jLabel12.setText("Jumlah Terlambat");

        jLabel13.setText("Jumlah Total Gaji jika Hari Kerja Kurang");

        jLabel14.setText("Jumlah Hadir Semua");

        jLabel15.setText("Total Potongan Terlambat");

        jLabel17.setText("Total Potong");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jumlahTotalGajiH))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jmTF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jtTF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jhsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(totalPotonganTerlambat, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(totalPotongan)))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jmTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jhsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jumlahTotalGajiH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(totalPotonganTerlambat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(totalPotongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hitungTotalBTN.setText("HITUNG TOTAL");
        hitungTotalBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungTotalBTNActionPerformed(evt);
            }
        });

        simpanBTN.setText("SIMPAN");
        simpanBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBTNActionPerformed(evt);
            }
        });

        clearBTN.setText("CLEAR");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        kembaliBTN.setText("KEMBALI");
        kembaliBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliBTNActionPerformed(evt);
            }
        });

        hitungBTN1.setText("HITUNG");
        hitungBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungBTN1ActionPerformed(evt);
            }
        });

        jLabel18.setText("Kode Karyawan");

        karyawanTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode Karyawan", "Nama Karyawan"
            }
        ));
        karyawanTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                karyawanTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(karyawanTB);

        kembaliBTN1.setText("CETAK");
        kembaliBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliBTN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addGap(18, 18, 18))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addGap(14, 14, 14)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(tahunTF, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(bulanTF, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel1))
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel18)
                                        .addGap(21, 21, 21)
                                        .addComponent(kdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(hitungBTN1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hitungTotalBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(simpanBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kembaliBTN1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kembaliBTN)
                                .addGap(18, 18, 18)
                                .addComponent(clearBTN)))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(bulanTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(tahunTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hitungTotalBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(simpanBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kembaliBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hitungBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kembaliBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(kdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1071, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GUI.admin.MainFrameAdmin mf = new GUI.admin.MainFrameAdmin();
        mf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void gajiPokokTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gajiPokokTFActionPerformed
                String queryGajiPokok = "SELECT gaji_pokok FROM karyawan INNER JOIN golongan ON karyawan.id_golongan = golongan.id_golongan WHERE karyawan.kode_karyawan = ?";
                try{
                    PreparedStatement statGajiPokok = koneksi.prepareStatement(queryGajiPokok);
                    statGajiPokok.setString(1, kdTF.getText());
                    ResultSet resultSetHadir = statGajiPokok.executeQuery();
                    resultSetHadir.next();
                    int gajiPokok = resultSetHadir.getInt(1);
                    gajiPokokTF.setText(""+gajiPokok);
                }catch (Exception e) {
                    System.out.println("Gagal " + e);
                }
    }//GEN-LAST:event_gajiPokokTFActionPerformed

    private void jmTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTFActionPerformed
        // TODO add your handling code here:
                String queryHadir = "SELECT COUNT(*) FROM rekap_absen WHERE MONTH(tanggal_absen) = ? AND YEAR(tanggal_absen) = ? AND kode_karyawan = ? AND keterangan IN ('Hadir', 'Terlambat', 'Pulang Awal', 'Tidak Terlambat')";
                try{
                    PreparedStatement preparedStatementHadir = koneksi.prepareStatement(queryHadir);
                    preparedStatementHadir.setString(1, bulanTF.getText());
                    preparedStatementHadir.setString(2, tahunTF.getText());
                    preparedStatementHadir.setString(3, kdTF.getText());
                    ResultSet resultSetHadir = preparedStatementHadir.executeQuery();
                    resultSetHadir.next();
                    int countHadir = resultSetHadir.getInt(1);
                    jmTF.setText(""+countHadir);
                }catch (Exception e) {
                    System.out.println("Gagal " + e.getMessage());
                }
                
    }//GEN-LAST:event_jmTFActionPerformed

    private void hitungBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungBTN1ActionPerformed
        // TODO add your handling code here:
        //Gaji Pokok
                String queryGajiPokok = "SELECT gaji_pokok FROM karyawan INNER JOIN golongan ON karyawan.id_golongan = golongan.id_golongan WHERE karyawan.kode_karyawan = ?";
                try{
                    PreparedStatement statGajiPokok = koneksi.prepareStatement(queryGajiPokok);
                    statGajiPokok.setString(1, kdTF.getText());
                    ResultSet resultSetHadir = statGajiPokok.executeQuery();
                    resultSetHadir.next();
                    int gajiPokok = resultSetHadir.getInt(1);
                    gajiPokokTF.setText(""+gajiPokok);
                }catch (Exception e) {
                    System.out.println("Gagal " + e);
                }
                
                //Hadir
                String queryHadir = "SELECT COUNT(*) FROM rekap_absen WHERE MONTH(tanggal_absen) = ? AND YEAR(tanggal_absen) = ? AND kode_karyawan = ? AND keterangan IN ('Hadir','Pulang Awal', 'Tidak Terlambat')";
                try{
                    PreparedStatement preparedStatementHadir = koneksi.prepareStatement(queryHadir);
                    preparedStatementHadir.setString(1, bulanTF.getText());
                    preparedStatementHadir.setString(2, tahunTF.getText());
                    preparedStatementHadir.setString(3, kdTF.getText());
                    ResultSet resultSetHadir = preparedStatementHadir.executeQuery();
                    resultSetHadir.next();
                    int countHadir = resultSetHadir.getInt(1);
                    jmTF.setText(""+countHadir);
                }catch (Exception e) {
                    System.out.println("Gagal " + e.getMessage());
                }
                
                //Terlambat
                String queryTerlambat = "SELECT COUNT(*) FROM rekap_absen WHERE MONTH(tanggal_absen) = ? AND YEAR(tanggal_absen) = ? AND kode_karyawan = ? AND keterangan IN ('Terlambat')";
                try{
                    PreparedStatement statTerlambat = koneksi.prepareStatement(queryTerlambat);
                    statTerlambat.setString(1, bulanTF.getText());
                    statTerlambat.setString(2, tahunTF.getText());
                    statTerlambat.setString(3, kdTF.getText());
                    ResultSet resultSetTerlambat = statTerlambat.executeQuery();
                    resultSetTerlambat.next();
                    int countTerlambat = resultSetTerlambat.getInt(1);
                    jtTF.setText("" + countTerlambat);
                }catch (Exception e) {
                    System.out.println("Gagal " + e.getMessage());
                }
                
                //Jumlah Total Hadir
                String queryHadirTotal = "SELECT COUNT(*) FROM rekap_absen WHERE MONTH(tanggal_absen) = ? AND YEAR(tanggal_absen) = ? AND kode_karyawan = ?";
                try{
                    PreparedStatement statHadirTotal = koneksi.prepareStatement(queryHadirTotal);
                    statHadirTotal.setString(1, bulanTF.getText());
                    statHadirTotal.setString(2, tahunTF.getText());
                    statHadirTotal.setString(3, kdTF.getText());
                    ResultSet resultSetHadirTotal = statHadirTotal.executeQuery();
                    resultSetHadirTotal.next();
                    int countHadirTotal = resultSetHadirTotal.getInt(1);
                    jhsTF.setText("" + countHadirTotal);
                }catch (Exception e) {
                    System.out.println("Gagal " + e.getMessage());
                }
    }//GEN-LAST:event_hitungBTN1ActionPerformed

    private void hitungTotalBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungTotalBTNActionPerformed
        // TODO add your handling code here:
        double gajiPokok = Double.parseDouble(gajiPokokTF.getText());
        int kodeKaryawan = Integer.parseInt(kdTF.getText());
        int jumlahHadir = Integer.parseInt(jmTF.getText());
        int jumlahTerlambat = Integer.parseInt(jtTF.getText());
        int jumlahHadirTotal = Integer.parseInt(jhsTF.getText());

        
        int bulan = Integer.parseInt(bulanTF.getText());
        int tahun = Integer.parseInt(tahunTF.getText());
        
        YearMonth yearMonth = YearMonth.of(tahun, bulan);
        int jumlahHari = yearMonth.lengthOfMonth();
        
        int libu_m = jumlahHari - 4;
        
        //hitung Potong Terlambat
        int jpt = 50000;
        int hitungPotonganTerlambat = jumlahTerlambat * jpt;
        
        totalPotonganTerlambat.setText("" + hitungPotonganTerlambat);
        
        //hitung total gaji
        double gaji = ((double) jumlahHadirTotal / libu_m) * gajiPokok;

        // Membulatkan gaji ke nilai bulat terdekat
        long gajiBulat = Math.round(gaji);
        
        jumlahTotalGajiH.setText("" + gajiBulat);
        
        double totalpt = gajiBulat - hitungPotonganTerlambat;
        
        long totalPotonganB = Math.round(totalpt);
        
        totalPotongan.setText("" + totalPotonganB);
        
        int bonus = 0;
        if (!bonusTF.getText().isEmpty()) {
            bonus = Integer.parseInt(bonusTF.getText());
        }else{
            bonusTF.setText("0");
        }
        
        double hitungTotalGaji = totalpt + bonus;
        
        long TotalGaji = Math.round(hitungTotalGaji);
        
        totalTF.setText("" + TotalGaji);
    }//GEN-LAST:event_hitungTotalBTNActionPerformed

    private void kembaliBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliBTNActionPerformed
        // TODO add your handling code here:
        GUI.admin.DataPenggajian dk = new GUI.admin.DataPenggajian();
        dk.setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliBTNActionPerformed

    private void simpanBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBTNActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyyMMddHHmmss");
        String timeStamp = dateFormat.format(new Date());
        String kodeUnik = "PG" + timeStamp;
        
        
        int bulan = Integer.parseInt(bulanTF.getText());
        int tahun = Integer.parseInt(tahunTF.getText());
        int kd = Integer.parseInt(kdTF.getText());
        
        int gajiPokok = Integer.parseInt(gajiPokokTF.getText());
        int bonus = Integer.parseInt(bonusTF.getText());
        int totalGaji = Integer.parseInt(totalTF.getText());
        
        int jm = Integer.parseInt(jmTF.getText());
        int jt = Integer.parseInt(jtTF.getText());
        int jhs = Integer.parseInt(jhsTF.getText());
        int totalGajih = Integer.parseInt(jumlahTotalGajiH.getText());
        int totalPotonganT = Integer.parseInt(totalPotonganTerlambat.getText());
        int totalPotonganAll = Integer.parseInt(totalPotongan.getText());
        
        try{
            stat.executeUpdate("INSERT INTO `penggajian`(`kode_penggajian`,`bulan`, `tahun`, `kode_karyawan`, `jumlah_masuk`, `jumlah_terlambat`, `jumlah_hari_kerja`, `gaji_pokok`, `bonus`, `potongan_terlambat`, `potongan_hari_kerja`, `total_potongan`,`total_gaji`) VALUES ("
        + "'" + kodeUnik + "',"
        + "'" + bulan + "',"
        + "'" + tahun + "',"
        + "'" + kd + "',"
        + "'" + jm + "',"
        + "'" + jt + "',"
        + "'" + jhs + "',"
        + "'" + gajiPokok + "',"
        + "'" + bonus + "',"
        + "'" + totalPotonganT + "',"
        + "'" + totalGajih + "',"
        + "'" + totalPotonganAll + "',"
        + "'" + totalGaji + "')");

            
            kosongkan();
            table();
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Di Simpan");
        }catch(Exception e){
            System.out.println("Gagal Query: " + e.getMessage());
        }
        
        
    }//GEN-LAST:event_simpanBTNActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_clearBTNActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        GUI.MainFrame mf = new GUI.MainFrame();
        mf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        GUI.admin.DataKaryawan mf = new GUI.admin.DataKaryawan();
        mf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        GUI.admin.DataAbsen mf = new GUI.admin.DataAbsen();
        mf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        GUI.admin.DataIzin mf = new GUI.admin.DataIzin();
        mf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        GUI.admin.DataPenggajian mf = new GUI.admin.DataPenggajian();
        mf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tahunTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunTFActionPerformed

    private void karyawanTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanTBMouseClicked
        // TODO add your handling code here:
        int row = karyawanTB.getSelectedRow();
        if(row >= 0){
            kdTF.setText(karyawanTB.getValueAt(row, 1).toString());
        }
    }//GEN-LAST:event_karyawanTBMouseClicked

    private void kembaliBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliBTN1ActionPerformed
        // TODO add your handling code here:
        GUI.admin.CetakPenggajian dk = new GUI.admin.CetakPenggajian();
        dk.setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliBTN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelolaPenggajian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelolaPenggajian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelolaPenggajian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelolaPenggajian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelolaPenggajian().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bonusTF;
    private javax.swing.JTextField bulanTF;
    private javax.swing.JButton clearBTN;
    private javax.swing.JTextField gajiPokokTF;
    private javax.swing.JButton hitungBTN1;
    private javax.swing.JButton hitungTotalBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jhsTF;
    private javax.swing.JTextField jmTF;
    private javax.swing.JTextField jtTF;
    private javax.swing.JTextField jumlahTotalGajiH;
    private javax.swing.JTable karyawanTB;
    private javax.swing.JTextField kdTF;
    private javax.swing.JButton kembaliBTN;
    private javax.swing.JButton kembaliBTN1;
    private javax.swing.JButton simpanBTN;
    private javax.swing.JTextField tahunTF;
    private javax.swing.JTextField totalPotongan;
    private javax.swing.JTextField totalPotonganTerlambat;
    private javax.swing.JTextField totalTF;
    // End of variables declaration//GEN-END:variables
}
